name: Bevinding iPgb
description: Issue voor het opvoeren van een bevinding
title: "[onderwerp]"
labels: ["iPgb", "Bevinding"]
projects: ["iStandaarden/12"]
type: "Bevinding"
body:
- type: input
  id: topdesk
  attributes: 
    label: Topdesknr 
    placeholder: Topdesknummer
  validations:
    required: false
- type: markdown
  attributes:
    value: <hr>
- type: markdown
  attributes:
    value: "# Onderwerp Bevinding"
- type: textarea
  id: probleem
  attributes:
    label: Probleem omschrijving
    placeholder: Geef omschrijving van het probleem
  validations:
    required: true
- type: textarea
  id: wijziging
  attributes:
    label: Omschrijving verwachte resultaat
    placeholder: Beschrijf het verwachte resultaat
  validations:
    required: true
- type: dropdown
  id: impact_onderdelen
  attributes:
    label: Bevinding gevolgen voor het onderdeel/de onderdelen
    multiple: true
    options:
      - Codelijsten
      - Documentatie
      - Class model (Bericht)
      - Regels
      - XSD 
      - anders, (geef hieronder aan)
  validations:
    required: true
- type: input
  id: ander_onderdeel
  attributes:
    label: Welk ander onderdeel?
    description: Voor welk ander onderdeel heeft de bevinding gevolgen
- type: dropdown
  id: impact_partij
  attributes:
    label: Betrokken partij bevinding
    multiple: true
    options:
      - VWS
      - Gemeente
      - Zorgkantoor
      - Zorginstituut
      - SVB
      - anders, (geef aan bij contactpersoon)
  validations:
    required: true
- type: input
  id: andere_partij
  attributes:
    label: Andere betrokken partij 
    placeholder: Naam andere partij
- type: markdown
  attributes:
    value: |
      <hr>
- type: markdown
  attributes: 
    value: "# Contactgegevens indiener"
- type: dropdown
  id: indiener
  attributes:
    label: Indiener bevinding
    options:
      - VWS
      - Gemeente
      - Zorgkantoor
      - SVB
      - Softwareleverancier zorgkantoor
      - Softwareleverancier gemeente
      - Zorginstituut
      - anders, (geef aan bij contactpersoon)
  validations:
    required: true
- type: input
  id: contactpersoon
  attributes:
    label: Andere organisatie / contactpersoon
    placeholder: Naam andere organisatie / contactpersoon
- type: markdown
  attributes:
    value: <hr>
- type: markdown
  attributes:
    value: "# Conclusie, oplossing en uitwerking"
- type: textarea
  id: oplossing
  attributes:
    label: Oplossing
    placeholder: Ruimte voor beschrijving oplossing
- type: dropdown
  id: conclusie
  attributes:
    label: Conclusie
    options:
      - Doorvoeren oplossing
      - Verwerpen (bevinding niet gegrond)
- type: textarea
  id: uitwerking
  attributes:
    label: Uitwerking
    placeholder: |
      # Uitwerking bevinding

      ## Proces

      | Onderwerp | Mutatie | Oude situatie | Nieuwe situatie |
      | :--- | :--- | :--- | :--- |
      | <Proces naam> | <Toevoegen / Wijzigen / Verwijderen> | <Wat was er eerst?> | <Wat is er na het oplossen van deze bevinding?> |
      
      ## Berichtdefinitie
      
      | Onderwerp | Mutatie | Oude situatie | Nieuwe situatie |
      | :--- | :--- | :--- | :--- |
      | <bericht id>.<klasse id>.<element id> | <Toevoegen / Wijzigen / Verwijderen> | <Wat was er eerst?> | <Wat is er na het oplossen van deze bevinding?> |
      
      ## Regels
      
      | Onderwerp | Mutatie | Oude situatie | Nieuwe situatie |
      | :--- | :--- | :--- | :--- |
      | Regel id | <Toevoegen / Wijzigen / Verwijderen> | <Wat was er eerst?> | <Wat is er na het oplossen van deze bevinding?> |
      
      ## Codelijsten
      
      | Onderwerp | Mutatie | Oude situatie | Nieuwe situatie |
      | :--- | :--- | :--- | :--- |
      | <codelijst id> | <Toevoegen / Wijzigen / Verwijderen> | <Wat was er eerst?> | <Wat is er na het oplossen van deze bevinding?> |
      
      ## Casuïstiek
      
      | Onderwerp | Mutatie | Oude situatie | Nieuwe situatie |
      | :--- | :--- | :--- | :--- |
      | <casus id> | <Toevoegen / Wijzigen / Verwijderen> | <Wat was er eerst?> | <Wat is er na het oplossen van deze bevinding?> |
      
- type: input
  id: implementatie
  attributes:
    label: Implementatiemoment / Ingang gekozen oplossing
    placeholder: "[yyyy-mm-dd]/zo snel mogelijk/nvt"
- type: input
  id: publicatie
  attributes:
    label: Publicatiemoment
    placeholder: "[yyyy-mm-dd]/zo snel mogelijk/nvt"

