name: Wijzigingsverzoek iPgb + analyse
description: Issue voor het volgen van een Wijzigingsverzoek
title: "RFC #### - onderwerp"
labels: ["iPgb", "Wijzigingsverzoek"]
type: Wijzigingsverzoek
projects: ["iStandaarden/12"]
body:
- type: input
  id: portaalNr
  attributes:
    label: Portaal backlog nummer
    placeholder: Portaal backlog nummer
- type: markdown
  attributes:
    value: |
      <hr>
- type: textarea
  id: samenvatting
  attributes:
    label: Korte probleem omschrijving
    placeholder: Geef een korte omschrijving van het probleem.
    value: |
      ### Probleemstelling  

      **Omdat** <oorzaak probleem> **ervaar ik als** <wie heeft er last van> **het gevolg** dat <welk negatief gevolg heeft het probleem, liefst meetbaar, in elk geval concreet>.

      #### Toelichting
      
      <Eventuele extra toelichting rondom de probleemstelling>.

      #### Voorbeelden
      
      <Eventuele praktijkvoorbeelden die onderbouwen waarom dit echt een probleem is.>

      #### Aandachtspunten

      <Eventuele aandachtspunten bij de uitwerking van eventuele oplossingsrichtingen.>
      
  validations:
    required: true
- type: markdown
  attributes: 
    value: "## Aanvullende gegevens wijzigingsverzoek"
- type: dropdown
  id: indiener
  attributes:
    label: Indiener wijzigingsverzoek
    options:
      - VWS
      - Softwareleverancier gemeente
      - Softwareleverancier zorgkantoor
      - Gemeente
      - Zorgkantoor
      - SVB
      - Zorginstituut
      - anders, (geef aan bij contactpersoon)
  validations:
    required: true
- type: input
  id: contactpersoon
  attributes:
    label: Andere organisatie / contactpersoon
    placeholder: Naam andere organisatie / contactpersoon
- type: markdown
  attributes:
    value: |
      <hr>
- type: dropdown
  id: impact_partij
  attributes:
    label: Betrokken partij wijzigingsverzoek
    multiple: true
    options:
      - VWS
      - Gemeente
      - Zorgkantoor
      - SVB
      - Zorginstituut
      - anders, (geef aan bij contactpersoon)
  validations:
    required: true
- type: input
  id: andere_partij
  attributes:
    label: Andere betrokken partij 
    placeholder: Naam andere partij
- type: markdown
  attributes:
    value: |
      <hr>
- type: markdown
  attributes:
    value: "## Analyse"
- type: textarea
  id: analyse-huidige-situatie
  attributes:
    label: Huidige situatie
    placeholder: Geef een omschrijving de huidige situatie rondom het beschreven probleem.
    value: |
      ### Huidige situatie  

      <Geef een omschrijving de huidige situatie rondom het beschreven probleem.>
      
  validations:
    required: true
- type: textarea
  id: analyse-bezwaren-huidige-situatie
  attributes:
    label: Bezwaren huidige situatie
    placeholder: Geef een omschrijving van de bezwaren die kleven aan de huidige situatie rondom het beschreven probleem.
    value: |
      ### Bezwaren huidige situatie  

      <Geef een omschrijving van de bezwaren die kleven aan de huidige situatie rondom het beschreven probleem.>
      
  validations:
    required: true
- type: markdown
  attributes:
    value: "## Wijzigingsvoorstellen"
- type: textarea
  id: oplossingsrichtingen
  attributes:
    label: Oplossingsrichtingen
    placeholder: Noem de verschillende oplossingsrichtingen
    value: |
      ### Oplossingsrichting 1

      <Geef een omschrijving van eerste oplossingsrichting. Let op: geen detailuitwerking, maar wel voldoende functionele informatie zodat het voor de ketenpartijen duidelijk is.>

      | Oplossing | Voordeel / nadeel |
      | :--- | :--- |
      | 1. <korte samenvatting oplossingsrichting> | Voordeel: <beschrijving voordeel t.o.v. andere oplossingsrichtingen en huidige situatie> |
      | | Voordeel: <beschrijving volgend voordeel t.o.v. andere oplossingsrichtingen en huidige situatie> |
      | | Nadeel: <beschrijving nadeel t.o.v. andere oplossingsrichtingen en huidige situatie> |
      | | Nadeel: <beschrijving volgend nadeel t.o.v. andere oplossingsrichtingen en huidige situatie> |

      ### Oplossingrichting 2

      <Geef een omschrijving van de tweede oplossingsrichting.>

      | Oplossing | Voordeel / nadeel |
      | :--- | :--- |
      | 1. <korte samenvatting oplossingsrichting> | Voordeel: <beschrijving voordeel t.o.v. andere oplossingsrichtingen en huidige situatie> |
      | | Voordeel: <beschrijving volgend voordeel t.o.v. andere oplossingsrichtingen en huidige situatie> |
      | | Nadeel: <beschrijving nadeel t.o.v. andere oplossingsrichtingen en huidige situatie> |
      | | Nadeel: <beschrijving volgend nadeel t.o.v. andere oplossingsrichtingen en huidige situatie> |

      ### Oplossingsrichting 3

      Niets veranderen.

      | Oplossing | Voordeel / nadeel |
      | :--- | :--- |
      | 1. <korte samenvatting oplossingsrichting> | Voordeel: <beschrijving voordeel t.o.v. andere oplossingsrichtingen en huidige situatie> |
      | | Voordeel: <beschrijving volgend voordeel t.o.v. andere oplossingsrichtingen en huidige situatie> |
      | | Nadeel: <beschrijving nadeel t.o.v. andere oplossingsrichtingen en huidige situatie> |
      | | Nadeel: <beschrijving volgend nadeel t.o.v. andere oplossingsrichtingen en huidige situatie> |

      ### Advies aan de referentiegroep

      Het advies is om te kiezen voor oplossingsrichting <oplossingsrichting>.
      
validations:
    required: true
- type: markdown
  attributes:
    value: |
      ## Uitwerking wijzigingsvoorstel oplossingsrichting <oplossingsrichting>
- type: textarea
  id: uitwerking
  attributes:
    label: Uitwerking
    value: |
      ### Proces

      | Onderwerp | Oude situatie | Nieuwe situatie |
      | :--- | :--- | :--- |
      | Naam proces | Hoe werkt het nu? | Hoe werkt het straks? |

      ### Regels

      | Onderwerp | Mutatie | Oude situatie | Nieuwe situatie |
      | :--- | :--- | :--- | :--- |
      | <Regelcode of placeholder bij nieuwe regel> | <Wat gaan we afdwingen?> | <wat was de titel / documentatie van de regel?> | <wat wordt de nieuwe titel / documentatie van de regel?> |

      ### Berichtdefinitie

      | Onderwerp | Mutatie | Oude situatie | Nieuwe situatie |
      | :--- | :--- | :--- | :--- |
      | <Berichtcode of placeholder bij nieuw bericht> | <Wat verandert er?> | <Hoe was het eerst gemodeleerd?> | <Hoe wordt de nieuwe opzet?> |

      ### Codelijsten

      | Onderwerp | Mutatie | Oude situatie | Nieuwe situatie |
      | :--- | :--- | :--- | :--- |
      | <Codelijst id> | <Wat verandert er?> | <Hoe was het eerst?> | <Hoe wordt het? |

      ### Casu&iuml;stiek

      | Onderwerp | Mutatie | Oude situatie | Nieuwe situatie |
      | :--- | :--- | :--- | :--- |
      | <Casus id> | <Wat verandert er?> | <Hoe was het eerst?> | <Hoe wordt het? |
      
- type: markdown
  attributes:
    value: |
      <hr>
- type: markdown
  attributes:
    value: "# Conclusie"
- type: input
  id: advies-stuurgroep
  attributes:
    label: Advies aan de stuurgroep
- type: input
  id: conclusie-stuurgroep
  attributes:
    label: Conclusie stuurgroep
- type: input
  id: implementatie
  attributes:
    label: Implementatiemoment
    placeholder: "[yyyy-mm-dd]/zo snel mogelijk/nvt"
- type: input
  id: publicatie
  attributes:
    label: Publicatiemoment
    placeholder: "[yyyy-mm-dd]/zo snel mogelijk/nvt"
- type: markdown
  attributes:
    value: |
      <hr>
- type: checkboxes
  id: project_values
  attributes:
    label: controleer project en labels van het issue
    options:
      - label: gecontroleerd
        required: true
